{"name": "Verify Calculation", "status": "failed", "statusDetails": {"message": "Failed: An error has occurred...see details:", "trace": "self = <selenium_automation.lesson03.super_calculator_v1.Test_Super_Calculator_V1 object at 0x00000293A1AFBFD0>\n\n    @allure.title(\"Verify Calculation\")\n    @allure.description(\"The function will keep calculating until provided number\")\n    def test_calculate(self):\n        try:\n>           self.calculate()\n\nlesson03\\super_calculator_v1.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\na = (<selenium_automation.lesson03.super_calculator_v1.Test_Super_Calculator_V1 object at 0x00000293A1AFBFD0>,), kw = {}, __tracebackhide__ = True\nparams = OrderedDict(), args = ['<selenium_automation.lesson03.super_calculator_v1.Test_Super_Calculator_V1 object at 0x00000293A1AFBFD0>']\n\n    @wraps(func)\n    def impl(*a, **kw):\n        __tracebackhide__ = True\n        params = func_parameters(func, *a, **kw)\n        args = list(map(lambda x: represent(x), a))\n        with StepContext(self.title.format(*args, **params), params):\n>           return func(*a, **kw)\nE           TypeError: Test_Super_Calculator_V1.calculate() missing 1 required positional argument: 'max_number'\n\n..\\venv\\lib\\site-packages\\allure_commons\\_allure.py:172: TypeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <selenium_automation.lesson03.super_calculator_v1.Test_Super_Calculator_V1 object at 0x00000293A1AFBFD0>\n\n    @allure.title(\"Verify Calculation\")\n    @allure.description(\"The function will keep calculating until provided number\")\n    def test_calculate(self):\n        try:\n            self.calculate()\n            self.print_input()\n        except Exception as e:\n            self.attach_file()\n>           pytest.fail(\"An error has occurred...see details:\", e)\nE           Failed: An error has occurred...see details:\n\nlesson03\\super_calculator_v1.py:33: Failed"}, "description": "The function will keep calculating until provided number", "steps": [{"name": "Calculate until provided number", "status": "broken", "statusDetails": {"message": "TypeError: Test_Super_Calculator_V1.calculate() missing 1 required positional argument: 'max_number'\n", "trace": "  File \"c:\\automation\\python\\test_automation\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n"}, "start": 1639474162162, "stop": 1639474162162}, {"name": "Attaching a screenshot to the report", "status": "passed", "attachments": [{"source": "95d8fe0a-a95e-45a1-8639-e41a18772fe7-attachment.png", "type": "image/png"}], "start": 1639474162163, "stop": 1639474162489}], "attachments": [{"name": "log", "source": "b1d5e15d-a6d6-43af-a99c-c40f50c4a942-attachment.txt", "type": "text/plain"}], "start": 1639474162162, "stop": 1639474162489, "uuid": "568d3042-663f-4846-9d93-373ae0d3e2b1", "historyId": "b1ebeee977e2501f2b137d4a6981cd53", "testCaseId": "68d98becfbabe45c5c0bd9775a8cd212", "fullName": "lesson03.super_calculator_v1.Test_Super_Calculator_V1#test_calculate", "labels": [{"name": "parentSuite", "value": "lesson03"}, {"name": "suite", "value": "super_calculator_v1"}, {"name": "subSuite", "value": "Test_Super_Calculator_V1"}, {"name": "host", "value": "DESKTOP-LVSINNE"}, {"name": "thread", "value": "10724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "lesson03.super_calculator_v1"}]}